default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: articles_development
  username: root
  password: nyros@123
test:
  <<: *default
  database: articles_test
  username: article-blog
  password: <%= ENV['ARTICLE-BLOG_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: articles_production
  username: articles-blog
  password: <%= ENV['ARTICLES-BLOG_DATABASE_PASSWORD'] %>
